const List<String> vietnamProvinces = [
  'An Giang',
  'Bà Rịa - Vũng Tàu',
  'Bạc Liêu',
  'Bắc Giang',
  'Bắc Kạn',
  'Bắc Ninh',
  'Bến Tre',
  'Bình Dương',
  'Bình Định',
  'Bình Phước',
  'Bình Thuận',
  'Cà Mau',
  'Cao Bằng',
  'Cần Thơ',
  'Đà Nẵng',
  'Đắk Lắk',
  'Đắk Nông',
  'Điện Biên',
  'Đồng Nai',
  'Đồng Tháp',
  'Gia Lai',
  'Hà Giang',
  'Hà Nam',
  'Hà Nội',
  'Hà Tĩnh',
  'Hải Dương',
  'Hải Phòng',
  'Hậu Giang',
  'Hòa Bình',
  'Hưng Yên',
  'Khánh Hòa',
  'Kiên Giang',
  'Kon Tum',
  'Lai Châu',
  'Lâm Đồng',
  'Lạng Sơn',
  'Lào Cai',
  'Long An',
  'Nam Định',
  'Nghệ An',
  'Ninh Bình',
  'Ninh Thuận',
  'Phú Thọ',
  'Phú Yên',
  'Quảng Bình',
  'Quảng Nam',
  'Quảng Ngãi',
  'Quảng Ninh',
  'Quảng Trị',
  'Sóc Trăng',
  'Sơn La',
  'Tây Ninh',
  'Thái Bình',
  'Thái Nguyên',
  'Thanh Hóa',
  'Thừa Thiên Huế',
  'Tiền Giang',
  'Hồ Chí Minh',
  'Trà Vinh',
  'Tuyên Quang',
  'Vĩnh Long',
  'Vĩnh Phúc',
  'Yên Bái',
];
// const List<String> vietnamProvinces = [
//   'An Giang',
//   'Ba Ria - Vung Tau',
//   'Bac Lieu',
//   'Bac Giang',
//   'Bac Kan',
//   'Bac Ninh',
//   'Ben Tre',
//   'Binh Duong',
//   'Binh Dinh',
//   'Binh Phuoc',
//   'Binh Thuan',
//   'Ca Mau',
//   'Cao Bang',
//   'Can Tho',
//   'Da Nang',
//   'Dak Lak',
//   'Dak Nong',
//   'Dien Bien',
//   'Dong Nai',
//   'Dong Thap',
//   'Gia Lai',
//   'Ha Giang',
//   'Ha Nam',
//   'Ha Noi',
//   'Ha Tinh',
//   'Hai Duong',
//   'Hai Phong',
//   'Hau Giang',
//   'Hoa Binh',
//   'Hung Yen',
//   'Ho Chi Minh',
//   'Khanh Hoa',
//   'Kien Giang',
//   'Kon Tum',
//   'Lai Chau',
//   'Lam Dong',
//   'Lang Son',
//   'Lao Cai',
//   'Long An',
//   'Nam Dinh',
//   'Nghe An',
//   'Ninh Binh',
//   'Ninh Thuan',
//   'Phu Tho',
//   'Phu Yen',
//   'Quang Binh',
//   'Quang Nam',
//   'Quang Ngai',
//   'Quang Ninh',
//   'Quang Tri',
//   'Soc Trang',
//   'Son La',
//   'Tay Ninh',
//   'Thai Binh',
//   'Thai Nguyen',
//   'Thanh Hoa',
//   'Thua Thien Hue',
//   'Tien Giang',
//   'Tra Vinh',
//   'Tuyen Quang',
//   'Vinh Long',
//   'Vinh Phuc',
//   'Yen Bai',
// ];
